apiVersion: v1
kind: Secret
metadata:
  name: %APP_NAME%-auth
  namespace: %KUBERNETES_NAMESPACE%
type: Opaque
stringData:
  host: %SENDGRID_HOST%
  username: %SENDGRID_USERNAME%
  apikey: %SENDGRID_API_KEY%
  sender-name: %SENDGRID_SENDER_NAME%
  sender-email: %SENDGRID_SENDER_EMAIL%
