name: Build and Deploy
on:
  pull_request:
    branches:
      - master 
  push:
    branches:
      - master 
env:
  APP_NAME: grafana
  VERSION: '${{ vars.VERSION }}.${{ github.run_number }}.${{ github.run_attempt }}'
  CHART_VERSION: 12.3.3
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }} 
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }} 
  AZURE_GROUP_KUBERNETES: ${{ vars.AZURE_RESOURCE_GROUP_KUBERNETES }} 
  AZURE_GROUP_DATABASE: ${{ vars.AZURE_RESOURCE_GROUP_DATABASE }} 
  AZURE_GROUP_DNS: ${{ vars.AZURE_RESOURCE_GROUP_DNS }} 
  AZURE_SUBSCRIPTION_ID: ${{ github.ref == 'refs/heads/master' && secrets.PRODUCTION_AZURE_SUBSCRIPTION_ID || secrets.STAGING_AZURE_SUBSCRIPTION_ID }}
  KUBERNETES_NODEPOOL_COMPUTE: cpu
  KUBERNETES_NAMESPACE: ${{ vars.KUBERNETES_NAMESPACE }}
  KUBERNETES_REPLICA_COUNT: ${{ github.ref == 'refs/heads/master' && 3 || 2 }}  
  KUBERNETES_MEMORY_REQUEST: 384Mi
  KUBERNETES_MEMORY_LIMIT: 1152Mi 
  KUBERNETES_CPU_REQUEST: 100m
  KUBERNETES_CPU_LIMIT: 300m
  GRAFANA_ADMIN_USERNAME: ${{ github.ref == 'refs/heads/master' && secrets.PRODUCTION_GRAFANA_ADMIN_USERNAME || secrets.STAGING_GRAFANA_ADMIN_USERNAME }}
  GRAFANA_ADMIN_PASSWORD: ${{ github.ref == 'refs/heads/master' && secrets.PRODUCTION_GRAFANA_ADMIN_PASSWORD || secrets.STAGING_GRAFANA_ADMIN_PASSWORD }}
  SQL_TYPE: mysql
  SQL_NAME: grafana
  SQL_USER: grafana-user
  SQL_ADMIN_PASSWORD: ${{ github.ref == 'refs/heads/master' && secrets.PRODUCTION_SQL_ADMIN_PASSWORD || secrets.STAGING_SQL_ADMIN_PASSWORD }}
  SUB_DOMAIN_NAME: grafana
jobs:
  build-and-deploy:
    runs-on:
      - self-hosted
      - linux 
      - ${{ github.ref == 'refs/heads/master' && 'Production' || 'Staging' }}
    permissions:
      contents: write
    concurrency:
      group: ${{ github.repository }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6

      - name: Azure Login
        shell: pwsh
        run: |
          az login --service-principal -u $env:AZURE_CLIENT_ID -p $env:AZURE_CLIENT_SECRET --tenant $env:AZURE_TENANT_ID -o none;
          az account set -s $env:AZURE_SUBSCRIPTION_ID -o none;

          $env:KUBERNETES_CLUSTER = az aks list -g $env:AZURE_GROUP_KUBERNETES --query [0].name -o tsv;
          az aks get-credentials -g $env:AZURE_GROUP_KUBERNETES -n $env:KUBERNETES_CLUSTER -o none;

      - name: Initialize MySQL Database
        if: env.SQL_TYPE == 'mysql'
        shell: pwsh
        run: |
          $env:SQL_HOST = az mysql flexible-server list -g $env:AZURE_GROUP_DATABASE --query [0].fullyQualifiedDomainName -o tsv;
          $env:SQL_PORT = az mysql flexible-server list -g $env:AZURE_GROUP_DATABASE --query [0].databasePort -o tsv;
          $env:SQL_ADMIN_USER = az mysql flexible-server list -g $env:AZURE_GROUP_DATABASE --query [0].administratorLogin -o tsv;
          $env:SQL_CA_CERT = Get-Content .sql/MySql/DigiCertGlobalRootG2.crt.pem -Raw; 

          $env:MYSQL_PWD = $env:SQL_ADMIN_PASSWORD;

          mysql `
              --host $env:SQL_HOST `
              --port $env:SQL_PORT `
              --user $env:SQL_ADMIN_USER `
              --ssl-mode=REQUIRED `
              -e "CREATE DATABASE IF NOT EXISTS $env:SQL_NAME;";

          $userExists = mysql `
              --host $env:SQL_HOST `
              --port $env:SQL_PORT `
              --user $env:SQL_ADMIN_USER `
              --ssl-mode=REQUIRED `
              -e "SELECT EXISTS(SELECT 1 FROM mysql.user WHERE user = '$env:SQL_USER');";

          if ($userExists -eq 0) 
          {
             mysql `
                 --host $env:SQL_HOST `
                 --port $env:SQL_PORT `
                 --user $env:SQL_ADMIN_USER `
                 --ssl-mode=REQUIRED `
                 -e "CREATE USER '$env:SQL_USER'@'%' IDENTIFIED BY '$env:SQL_PASSWORD'; GRANT SELECT, INSERT, UPDATE, DELETE ON $env:SQL_NAME.* TO '$env:SQL_USER'@'%'; FLUSH PRIVILEGES;";
          }

          echo "SQL_HOST=$env:SQL_HOST" >> $env:GITHUB_ENV;
          echo "SQL_PORT=$env:SQL_PORT" >> $env:GITHUB_ENV;
          echo "SQL_ADMIN_USER=$env:SQL_ADMIN_USER" >> $env:GITHUB_ENV;
          echo "SQL_CA_CERT<<EOF`n$env:SQL_CA_CERT`nEOF" >> $env:GITHUB_ENV

      - name: Initialize PostgreSQL Database
        if: env.SQL_TYPE == 'postgresql'
        shell: pwsh
        run: |

      - name: Initialize SQL Server Database
        if: env.SQL_TYPE == 'sqlserver'
        shell: pwsh
        run: |

      - name: Deploy Grafana
        shell: pwsh
        run: |
          $zoneNames = az network dns zone list -g $env:AZURE_GROUP_DNS --query "[].name" -o json | ConvertFrom-Json

          $env:ROUTE_HOST_NAMES = (
              $zoneNames | ForEach-Object {
                  "  - $env:SUB_DOMAIN_NAME.$_"
              }
          ) -join "`n"

          $env:GATEWAY_NAME = kubectl get gateway -n $env:KUBERNETES_NAMESPACE -o jsonpath='{.items[0].metadata.name}'
          $env:SQL_CA_CERT_BASE64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($env:SQL_CA_CERT))

          Get-Content .kubernetes/grafana-db-auth-secret.yaml | foreach { [Environment]::ExpandEnvironmentVariables($_) } | Set-Content .kubernetes/grafana-db-auth-secret.tmp.yaml;
          kubectl apply -f .kubernetes/grafana-db-auth-secret.tmp.yaml;
          if ($LastExitCode -ne 0) 
          { 
              throw "error";
          }

          Get-Content .kubernetes/grafana-db-ca-cert-secret.yaml | foreach { [Environment]::ExpandEnvironmentVariables($_) } | Set-Content .kubernetes/grafana-db-ca-cert-secret.tmp.yaml;
          kubectl apply -f .kubernetes/grafana-db-ca-cert-secret.tmp.yaml;
          if ($LastExitCode -ne 0) 
          { 
              throw "error";
          }

          Get-Content .kubernetes/grafana-admin-auth-secret.yaml | foreach { [Environment]::ExpandEnvironmentVariables($_) } | Set-Content .kubernetes/grafana-admin-auth-secret.tmp.yaml;
          kubectl apply -f .kubernetes/grafana-admin-auth-secret.tmp.yaml;
          if ($LastExitCode -ne 0) 
          { 
              throw "error";
          }

          Get-Content .kubernetes/grafana-values.yaml | foreach { [Environment]::ExpandEnvironmentVariables($_) } | Set-Content .kubernetes/grafana-values.tmp.yaml;
          helm upgrade --install $env:APP_NAME oci://ghcr.io/grafana-community/helm-charts/grafana --namespace $env:KUBERNETES_NAMESPACE --version $env:CHART_VERSION -f .kubernetes/grafana-values.tmp.yaml;
          if ($LastExitCode -ne 0) 
          { 
              throw "error";
          }

          Get-Content .kubernetes/grafana-httproute-80.yaml | foreach { [Environment]::ExpandEnvironmentVariables($_) } | Set-Content .kubernetes/grafana-httproute-80.tmp.yaml;
          kubectl apply -f .kubernetes/grafana-httproute-80.tmp.yaml;
          if ($LastExitCode -ne 0) 
          { 
              throw "error";
          }

          Get-Content .kubernetes/grafana-httproute-443.yaml | foreach { [Environment]::ExpandEnvironmentVariables($_) } | Set-Content .kubernetes/grafana-httproute-443.tmp.yaml;
          kubectl apply -f .kubernetes/grafana-httproute-443.tmp.yaml;
          if ($LastExitCode -ne 0) 
          { 
              throw "error";
          }

          Get-Content .kubernetes/grafana-service-monitor.yaml | foreach { [Environment]::ExpandEnvironmentVariables($_) } | Set-Content .kubernetes/grafana-service-monitor.tmp.yaml;
          kubectl apply -f .kubernetes/grafana-service-monitor.tmp.yaml;
          if ($LastExitCode -ne 0) 
          { 
              throw "error";
          }

          Get-Content .kubernetes/grafana-healthcheck-policy.yaml | foreach { [Environment]::ExpandEnvironmentVariables($_) } | Set-Content .kubernetes/grafana-healthcheck-policy.tmp.yaml;
          kubectl apply -f .kubernetes/grafana-healthcheck-policy.tmp.yaml;
          if ($LastExitCode -ne 0) 
          { 
              throw "error";
          }

      - name: GitHub Release
        if: github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: |
            Version: ${{ env.VERSION }}
            Commit: ${{ github.sha }}
            Build run: ${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          
      - name: Slack Notification
        if: always()
        uses: act10ns/slack@v2
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          config: .github/config/slack.yml
          status: ${{ job.status }}
          channel: ${{ vars.SLACK_CHANNEL }}