name: Build and Deploy
on:
  pull_request:
    branches:
      - main 
  push:
    branches:
      - main 
  workflow_dispatch:
env:
  APP_NAME: rabbitmq
  VERSION: '${{ vars.VERSION }}.${{ github.run_number }}.${{ github.run_attempt }}'
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }} 
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }} 
  AZURE_GROUP_KUBERNETES: ${{ vars.AZURE_RESOURCE_GROUP_KUBERNETES }} 
  AZURE_SUBSCRIPTION_ID: ${{ github.ref == 'refs/heads/main' && secrets.PRODUCTION_AZURE_SUBSCRIPTION_ID || secrets.STAGING_AZURE_SUBSCRIPTION_ID }}
  KUBERNETES_NODEPOOL_COMPUTE: cpu
  KUBERNETES_NAMESPACE: ${{ vars.KUBERNETES_NAMESPACE }}
  KUBERNETES_REPLICA_COUNT: ${{ github.ref == 'refs/heads/main' && 3 || 2 }}  
  KUBERNETES_MEMORY_REQUEST: 384Mi
  KUBERNETES_MEMORY_LIMIT: 1152Mi 
  KUBERNETES_CPU_REQUEST: 100m
  KUBERNETES_CPU_LIMIT: 300m
  RABBITMQ_OPERATOR_VERSION: v2.21.1
  RABBITMQ_IMAGE_TAG: 4.3.2-management
  RABBITMQ_ADMIN_USERNAME: ${{ github.ref == 'refs/heads/main' && secrets.PRODUCTION_RABBITMQ_ADMIN_USERNAME || secrets.STAGING_RABBITMQ_ADMIN_USERNAME }}
  RABBITMQ_ADMIN_PASSWORD: ${{ github.ref == 'refs/heads/main' && secrets.PRODUCTION_RABBITMQ_ADMIN_PASSWORD || secrets.STAGING_RABBITMQ_ADMIN_PASSWORD }}
  RABBITMQ_ERLANG_COOKIE: ${{ github.ref == 'refs/heads/main' && secrets.PRODUCTION_RABBITMQ_ERLANG_COOKIE || secrets.STAGING_RABBITMQ_ERLANG_COOKIE }}
jobs:
  build-and-deploy:
    runs-on:
      - self-hosted
      - linux 
      - ${{ github.ref == 'refs/heads/main' && 'Production' || 'Staging' }}
    permissions:
      contents: write
    concurrency:
      group: ${{ github.repository }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v6

      - name: Azure Login
        shell: pwsh
        run: |
          az login --service-principal -u $env:AZURE_CLIENT_ID -p $env:AZURE_CLIENT_SECRET --tenant $env:AZURE_TENANT_ID -o none;
          az account set -s $env:AZURE_SUBSCRIPTION_ID -o none;

          $env:KUBERNETES_CLUSTER = az aks list -g $env:AZURE_GROUP_KUBERNETES --query [0].name -o tsv;
          az aks get-credentials -g $env:AZURE_GROUP_KUBERNETES -n $env:KUBERNETES_CLUSTER -o none;

      - name: Deploy RabbitMQ
        shell: pwsh
        run: |
          kubectl apply -f https://github.com/rabbitmq/cluster-operator/releases/download/$env:RABBITMQ_OPERATOR_VERSION/cluster-operator.yml;

          Get-Content .kubernetes/rabbitmq-cluster.yaml | foreach { [Environment]::ExpandEnvironmentVariables($_) } | Set-Content .kubernetes/rabbitmq-cluster.tmp.yaml;
          kubectl apply -f .kubernetes/rabbitmq-cluster.tmp.yaml;
          if ($LastExitCode -ne 0) 
          { 
              throw "error";
          }

          Get-Content .kubernetes/rabbitmq-auth-secret.yaml | foreach { [Environment]::ExpandEnvironmentVariables($_) } | Set-Content .kubernetes/rabbitmq-auth-secret.tmp.yaml;
          kubectl apply -f .kubernetes/rabbitmq-auth-secret.tmp.yaml;
          if ($LastExitCode -ne 0) 
          { 
              throw "error";
          }

          Get-Content .kubernetes/rabbitmq-load-definition-secret.yaml | foreach { [Environment]::ExpandEnvironmentVariables($_) } | Set-Content .kubernetes/rabbitmq-load-definition-secret.tmp.yaml;
          kubectl apply -f .kubernetes/rabbitmq-load-definition-secret.tmp.yaml;
          if ($LastExitCode -ne 0) 
          { 
              throw "error";
          }

          Get-Content .kubernetes/rabbitmq-service-monitor.yaml | foreach { [Environment]::ExpandEnvironmentVariables($_) } | Set-Content .kubernetes/rabbitmq-service-monitor.tmp.yaml;
          kubectl apply -f .kubernetes/rabbitmq-service-monitor.tmp.yaml;
          if ($LastExitCode -ne 0) 
          { 
              throw "error";
          }

      - name: Update Azure Policies
        shell: pwsh
        run: |
          $ports = @("5672","15672","15692","4369","25672");

          $currentPorts = @(az policy assignment show -n SecurityCenterBuiltIn --scope "/subscriptions/$env:AZURE_SUBSCRIPTION_ID" --query "parameters.allowedservicePortsInKubernetesClusterPorts.value[]" -o tsv | Where-Object { $_ -ne "-1" })
          $missingPorts = @($ports | Where-Object { $currentPorts -notcontains $_ })

          if ($missingPorts.Count -gt 0) {
              $mergedPorts = @(($currentPorts + $missingPorts) | Select-Object -Unique)

              $allParams = az policy assignment show -n SecurityCenterBuiltIn --scope "/subscriptions/$env:AZURE_SUBSCRIPTION_ID" --query "parameters" -o json | ConvertFrom-Json;
              $allParams.allowedservicePortsInKubernetesClusterPorts.value = $mergedPorts;

              $params = $allParams | ConvertTo-Json -Compress -Depth 100;

              az policy assignment update `
                  -n SecurityCenterBuiltIn `
                  --scope "/subscriptions/$env:AZURE_SUBSCRIPTION_ID" `
                  --params $params;
          }

      - name: GitHub Release
        if: github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: |
            Version: ${{ env.VERSION }}
            Commit: ${{ github.sha }}
            Build run: ${{ github.run_number }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false

      - name: Slack Notification
        if: always()
        uses: act10ns/slack@v2
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          config: .github/config/slack.yml
          status: ${{ job.status }}
          channel: ${{ vars.SLACK_CHANNEL }}