name: Build and Deploy
on:
  push
env:
  APP_NAME: rabbitmq
  VERSION: '${{ vars.VERSION }}.${{ github.run_number }}.${{ github.run_attempt }}'
  HELM_VERSION: 3.7
  CHART_VERSION: 14.6.7
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }} 
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }} 
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }} 
  AZURE_GROUP: ${{ vars.AZURE_KUBERNETES_RESOURCE_GROUP }} 
  AZURE_SUBSCRIPTION_ID: ${{ github.ref == 'refs/heads/master' && secrets.PRODUCTION_AZURE_SUBSCRIPTION_ID || secrets.STAGING_AZURE_SUBSCRIPTION_ID }}
  KUBERNETES_CLUSTER: ${{ github.ref == 'refs/heads/master' && vars.PRODUCTION_KUBERNETES_CLUSTER || vars.STAGING_KUBERNETES_CLUSTER }}
  KUBERNETES_NODEPOOL_COMPUTE: cpu
  KUBERNETES_NAMESPACE: apps
  KUBERNETES_REPLICA_COUNT: ${{ github.ref == 'refs/heads/master' && 3 || 2 }}  
  KUBERNETES_MEMORY_REQUEST: 128Mi
  KUBERNETES_MEMORY_LIMIT: 384Mi 
  KUBERNETES_CPU_REQUEST: 100m
  KUBERNETES_CPU_LIMIT: 300m
  RABBITMQ_ADMIN_USERNAME: rabbitmq_user
  RABBITMQ_ADMIN_PASSWORD: ${{ github.ref == 'refs/heads/master' && vars.PRODUCTION_RABBITMQ_ADMIN_PASSWORD || vars.STAGING_RABBITMQ_ADMIN_PASSWORD }}
  RABBITMQ_ERLANG_COOKIE: ${{ github.ref == 'refs/heads/master' && vars.PRODUCTION_RABBITMQ_ERLANG_COOKIE || vars.STAGING_RABBITMQ_ERLANG_COOKIE }}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    concurrency:
      group: ${{ github.repository }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - name: Deploy
        shell: pwsh
        run: |
          sudo az login --service-principal -u $env:AZURE_CLIENT_ID -p $env:AZURE_CLIENT_SECRET --tenant $env:AZURE_TENANT_ID -o none;
          sudo az account set -s $env:AZURE_SUBSCRIPTION_ID -o none;
          sudo az aks get-credentials -g $env:AZURE_GROUP -n $env:KUBERNETES_CLUSTER -o none;

          az aks command invoke `
            -g $env:AZURE_GROUP `
            -n $env:KUBERNETES_CLUSTER `
            --command @"
          \$ErrorActionPreference = 'Stop'

          Write-Host 'Installing Helm...';
          apt-get update -y;
          apt-get install snapd -y;
          snap install helm --channel=$env:HELM_VERSION --classic;

          Write-Host 'Adding Helm repo...';
          helm repo add bitnami https://charts.bitnami.com/bitnami;
          helm repo update;

          Write-Host 'Rendering Kubernetes manifest...'
          Get-Content .kubernetes/rabbitmq-load-definition-secret.yaml | ForEach-Object { [Environment]::ExpandEnvironmentVariables(\$_) } | Set-Content .kubernetes/rabbitmq-load-definition-secret.tmp.yaml;

          Write-Host 'Applying Kubernetes manifest...'
          kubectl apply -f .kubernetes/rabbitmq-load-definition-secret.tmp.yaml;

          if ($LastExitCode -ne 0) 
          {
              throw "kubectl apply failed";
          }

          Write-Host 'Checking Helm release...';
          \$exists = helm list --namespace $env:KUBERNETES_NAMESPACE --filter $env:APP_NAME;

          \$parameters = @(
              "--version", $env:CHART_VERSION,
              "--namespace", $env:KUBERNETES_NAMESPACE,
              "--set", "replicaCount=$env:KUBERNETES_REPLICA_COUNT",
              "--set", "podAntiAffinityPreset=hard",
              "--set", "clustering.forceBoot=true",
              "--set", "containerSecurityContext.allowPrivilegeEscalation=false",
              "--set", "auth.username=$env:RABBITMQ_ADMIN_USERNAME",
              "--set", "auth.password=$env:RABBITMQ_ADMIN_PASSWORD",
              "--set", "auth.erlangCookie=$env:RABBITMQ_ERLANG_COOKIE",
              "--set", "nodeSelector.kubernetes\.io\/os=linux",
              "--set", "nodeSelector.nodepool\.compute=$env:KUBERNETES_NODEPOOL_COMPUTE",
              "--set", "resources.requests.cpu=$env:KUBERNETES_CPU_REQUEST",
              "--set", "resources.requests.memory=$env:KUBERNETES_MEMORY_REQUEST",
              "--set", "resources.limits.cpu=$env:KUBERNETES_CPU_LIMIT",
              "--set", "resources.limits.memory=$env:KUBERNETES_MEMORY_LIMIT",
              "--set", "metrics.enabled=true",
              "--set", "loadDefinition.enabled=true",
              "--set", "loadDefinition.existingSecret=rabbitmq-load-definition-secret"
          );

          if (\$exists) 
          {
              Write-Host 'Upgrading Helm release...';
              helm upgrade $env:APP_NAME bitnami/rabbitmq @parameters;
          }
          else 
          {
              Write-Host 'Installing Helm release...';
              helm install $env:APP_NAME bitnami/rabbitmq @parameters;
          }
          "@ -o none;

      - name: GitHub Release
        if: github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: |
            Version: ${{ env.VERSION }}
            Commit: ${{ github.sha }}
          artifacts: "nupkgs/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
